# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ef9e38228d133e9deb76765f620d07afaeb43c5e280185ef4c5af2213e18d66b9ac66cf1f3590e93db51770e004c71c5132557ced4eb1c98b6fd9553ea55c4b

test:
  secret_key_base: 353b2bbd27c707f5f020e66f9f0ae9f1e963e393d8a70304ede9a9bab8e02a67818c8110884498dec6cb151504610e2781b7763ec8b90521f81beed8f740c2f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
