# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb0f73fd8951cbf2f72c403b745a495a0f30ca4010497ab83a19ec826cb31fd7d3b771e644eb6d5eb8102004138f21e278f94343cf1ff858da89f2d3a6840926

test:
  secret_key_base: 28721ededf23352856b2c16b3b8ae089c16511ee41d69cea701694a0575a0d79e9ad2e72e79d3775da2d911678824f2005e9a955b79f563ca4d20dd55aad8ef7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
